#!/usr/bin/env python3
"""
Regenerate docs/PAPER_TRADING.md from the live Alpaca paper account.

Pulls account equity, current positions, and the full daily portfolio-history
curve, benchmarks the same window against SPY and QQQ (Nasdaq-100), and writes a
Markdown performance report.

Usage:
    python scripts/fetch_paper_performance.py            # paper account (default)
    python scripts/fetch_paper_performance.py --live     # live account

Requires ALPACA_API_KEY / ALPACA_SECRET_KEY in the environment or .env.
"""
import os
import sys
import argparse
import datetime as dt
from urllib.request import Request, urlopen
import ssl
import json

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    import certifi
    _SSL_CTX = ssl.create_default_context(cafile=certifi.where())
except Exception:
    _SSL_CTX = ssl.create_default_context()


def _load_env():
    env_file = os.path.join(_ROOT, ".env")
    if os.path.exists(env_file):
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    os.environ.setdefault(k.strip(), v.strip())


def _api(base, path, key, secret):
    req = Request(base + path, headers={
        "APCA-API-KEY-ID": key,
        "APCA-API-SECRET-KEY": secret,
    })
    with urlopen(req, timeout=30, context=_SSL_CTX) as r:
        return json.load(r)


def _benchmark_returns(start_date, end_date):
    """Return {'SPY': pct, 'QQQ': pct} over [start, end], or None if unavailable."""
    try:
        import yfinance as yf
    except Exception:
        return None
    out = {}
    for sym in ("SPY", "QQQ"):
        try:
            s = yf.Ticker(sym).history(start=start_date, end=end_date + dt.timedelta(days=2),
                                       auto_adjust=True)["Close"].dropna()
            if len(s) > 1:
                out[sym] = (s.iloc[-1] / s.iloc[0] - 1) * 100
        except Exception:
            pass
    return out or None


def build_report(paper=True):
    _load_env()
    key = os.environ.get("ALPACA_API_KEY")
    secret = os.environ.get("ALPACA_SECRET_KEY")
    if not key or not secret:
        sys.exit("Missing ALPACA_API_KEY / ALPACA_SECRET_KEY (set in .env)")
    base = "https://paper-api.alpaca.markets" if paper else "https://api.alpaca.markets"

    account = _api(base, "/v2/account", key, secret)
    positions = _api(base, "/v2/positions", key, secret)
    hist = _api(base, "/v2/account/portfolio/history?period=all&timeframe=1D", key, secret)

    equity = float(account["equity"])
    last_equity = float(account["last_equity"])
    cash = float(account["cash"])
    created = account["created_at"][:10]

    eq = [e for e in (hist.get("equity") or []) if e]
    ts = hist.get("timestamp") or []
    base_value = float(hist.get("base_value") or (eq[0] if eq else 0))
    first_date = dt.datetime.fromtimestamp(ts[0], dt.timezone.utc).date() if ts else None
    last_date = dt.datetime.fromtimestamp(ts[-1], dt.timezone.utc).date() if ts else None
    peak = base_value
    mdd = 0.0
    for v in eq:
        peak = max(peak, v)
        mdd = min(mdd, v / peak - 1)
    total_ret = (equity / base_value - 1) * 100 if base_value else 0.0
    peak_eq = max(eq) if eq else equity

    bench = _benchmark_returns(first_date, last_date) if first_date else None

    pos = sorted(positions, key=lambda p: -float(p["market_value"]))
    invested = sum(float(p["market_value"]) for p in pos)

    today = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L = []
    a = L.append
    a("# Live Paper-Trading Performance\n")
    a("> Auto-generated by `scripts/fetch_paper_performance.py` from the live Alpaca "
      "paper account. **Past performance does not guarantee future results.**\n")
    a(f"**Snapshot:** {today}  |  **Account opened:** {created}  |  "
      f"**Mode:** {'Paper' if paper else 'LIVE'}\n")
    a("## Headline\n")
    a("| Metric | Value |")
    a("|--------|-------|")
    a(f"| Starting capital | ${base_value:,.0f} |")
    a(f"| Current equity | ${equity:,.0f} |")
    a(f"| Peak equity | ${peak_eq:,.0f} |")
    a(f"| **Total return** | **{total_ret:+.1f}%** |")
    a(f"| Prior close equity | ${last_equity:,.0f} ({(equity/last_equity-1)*100:+.2f}% today) |")
    a(f"| Max drawdown | {mdd*100:.1f}% |")
    a(f"| Cash | ${cash:,.0f} |")
    a(f"| Open positions | {len(pos)} |")
    if first_date:
        a(f"| Window | {first_date} → {last_date} |")
    a("")

    if bench:
        a("## Same-window benchmark comparison\n")
        a("| | Return |")
        a("|--|--------|")
        a(f"| **Strategy (paper)** | **{total_ret:+.1f}%** |")
        for sym, label in (("SPY", "S&P 500 (SPY)"), ("QQQ", "Nasdaq-100 (QQQ)")):
            if sym in bench:
                a(f"| {label} | {bench[sym]:+.1f}% |")
        a("")

    a("## Top holdings\n")
    a("| Ticker | Market value | Weight | Unrealized P/L |")
    a("|--------|-------------:|-------:|---------------:|")
    for p in pos[:15]:
        mv = float(p["market_value"])
        w = mv / invested * 100 if invested else 0
        upl = float(p["unrealized_plpc"]) * 100
        a(f"| {p['symbol']} | ${mv:,.0f} | {w:.1f}% | {upl:+.1f}% |")
    if len(pos) > 15:
        a(f"| … +{len(pos)-15} more | | | |")
    a("")

    # Equity curve (sampled, ~weekly) so the table stays readable
    if eq:
        a("## Equity curve (weekly samples)\n")
        a("| Date | Equity |")
        a("|------|-------:|")
        step = max(1, len(eq) // 14)
        for i in range(0, len(eq), step):
            d = dt.datetime.fromtimestamp(ts[i], dt.timezone.utc).date()
            a(f"| {d} | ${eq[i]:,.0f} |")
        if (len(eq) - 1) % step:
            a(f"| {last_date} | ${eq[-1]:,.0f} |")
        a("")

    a("---")
    a("*Strategy details in [STRATEGY.md](STRATEGY.md); backtest in "
      "[BACKTEST_RESULTS.md](BACKTEST_RESULTS.md).*")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--live", action="store_true", help="Use the live account instead of paper")
    ap.add_argument("--out", default=os.path.join(_ROOT, "docs", "PAPER_TRADING.md"))
    args = ap.parse_args()
    report = build_report(paper=not args.live)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(report)
    print(f"Wrote {args.out}")


if __name__ == "__main__":
    main()
